apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wap862d9z-nodejs
  janus-idp.io/tekton: wap862d9z-nodejs
  backstage.io/kubernetes-id: wap862d9z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wap862d9z-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
